# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25eafb38b6b3165dc6af6e0168909fdff7abffac9fbebe78d426f81228a0ff9815f0a3aaa9da0d12d44bcb7f444e29ee6e5f938dcdd37378025a6f5b56cda4e5

test:
  secret_key_base: 6489e1cd79e2c1aa580a7e830922776dc19f63f9300f52bb8b495f1c1de9c13d362a20d7aa3cffe85939058f2b4cf9784efddb2a86072112e91cbcf321dc8973

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
